### PR TITLE
Added new parameters --minins and --maxins

### PR DESCRIPTION
**Pull request by ewels**
Added new parameters `--minins` and `--maxins` to the pipeline, passed on to Bismark. These are needed to process EM-seq libraries.

## PR checklist

- [x] This comment contains a description of changes (with reason)
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker`).
- [ ] Make sure your code lints (`nf-core lint .`).
- [x] Documentation in `docs` is updated
- [x] `CHANGELOG.md` is updated

### CODE REVIEW

**Comment by phue** [comment]
Hi @ewels ,
could you explain _why_ this is needed for EMseq libraries specifically? I'm wondering if it would make sense to set these to sensible defaults and specify them using a `--em_seq` parameter instead.
For example: `def emseq =  params.em_seq ? "--minins XX --maxins XX" : ""`

**Comment by ewels** [comment]
Sure - EM-seq libraries have a larger insert size as compared to regular bisulfite data, so adjusting the insert size might improve the alignments.

I was / am hoping to also provide an `--em_seq` preset as you say, but haven't yet heard back about what sensible defaults might be. I figured that adding these options in the mean time would make it easier to settle on those numbers 😁 I figure that it doesn't have to be either / or.

**Comment by phue** [comment]
Alright thanks. That sounds reasonable.

**Review by phue — APPROVED** [review]

**Comment by FelixKrueger** [comment]
I just checked my email conversations and the only mention of EM-seq and insert sizes I found was that reads were on average 350bp. If this were the case, then `-X 1000` should be sufficient as a start (even though in that particular case it didn't really add much to the default mapping rate. Once you have one test dataset at hand it is easy enough to check the insert sizes, and (up-)correct the values if needed.

**Comment by ewels** [comment]
Thanks both 👍🏻 - just heard back that we were trying with `-X 800` and trimming 8bp from both ends of all reads. So `-X 1000` sounds sensible. I'll add on a preset for this.

**Comment by ewels** [comment]
If I could just have a second 👍🏻 from @phue or @FelixKrueger with this latest change for the new preset, that would be fab! Then I'll merge..

**Comment by ewels** [comment]
(or feel free to take a look and merge yourselves)

**Pull request merged**
