### PR TITLE
nf-hack18: fix nondeterministic execution of bismark_report

### PR DESCRIPTION
**Pull request by phue**
Hi,

I tried to implement the fix for #48  as suggested by @pditommaso 

I hope I didn't overcomplicate things. Please review :)

Cheers,
Patrick

### CODE REVIEW

**Comment by pditommaso** [comment]
I've tested locally now works as expected, no more non-deterministic resume!

**Comment by pditommaso** [comment]
Thanks for your PR! also my first merge on nf-core 🤓

**Comment by ewels** [comment]
Awesome stuff - thanks both!

@phue - only thing you missed was an entry in `CHANGELOG.md`. I'll add that now. When we finally sync with the master template we will get issue templates that have reminders for this stuff.

We should push a new release ASAP after this fix.

**Comment by phue** [comment]
Great, I'll keep that in mind for the next PR :+1:

**Pull request merged**
