### PR TITLE
Run tests on changes

### PR DESCRIPTION
**Pull request by Emiller88**
No idea if this will work if we merge it 🤷🏻

### CODE REVIEW

**Review by mashehu — APPROVED** [review]
Do we also need to consider changes in nextflow-schema.json? I can't think how something there could break a test, but maybe there is?

**Comment by Emiller88** [comment]
Good catch. We should probably run the tests if anything changes in `test`...

**Review by jfy133 — COMMENTED** [review]
What about changes to the ci test files as well?

`.github/workflows/*` or something?

**Comment by sateeshperi** [comment]
now that we are transitioning to nf-test, lets explore using this paths and nf-test tags in a separate PR. would request closing this PR @Emiller88

**Pull request closed without merging**
