### PR TITLE
bismark: add support for hisat2 alignment

### PR DESCRIPTION
**Pull request by phue**
Addresses https://github.com/nf-core/methylseq/issues/85

Since bismark v0.21.0 , alignment using HISAT2 is supported in addition to Bowtie2.

As suggested by @ewels it can be run using `--aligner bismark_hisat`

I added the required steps for bismark_genome_preparation and bismark alignment. 
Supplying a file containing list of known splicesites should work as well with the `--known_splices` flag but is not very useful as of now because the pipeline can't handle RNA samples yet. We should probably also add support for bismark's `--slam` flag to make it more useful for SLAM-seq usecases.

Also there are some sanity checks missing to prevent breakage e.g if accidentally bowtie2 indices are supplied together with `--aligner bismark_hisat`. This can be done by checking the file endings I suppose.

### CODE REVIEW

**Comment by ewels** [comment]
And yes, adding in a `--slam` option would also be good, especially if it's only one extra `params` (though dependent on using the hisat aligner I guess).

I'm not hugely fussed about checking that people are supplying the correct references. It would certainly be nice, but we haven't had that so far and no-one has complained 😉

**Comment by FelixKrueger** [comment]
Thanks @phue for adding these changes. Just for the record, Bismark itself performs sanity checks for the indexes, so the pipeline should fail very early on in case they were mis-specified.

And no, `--slam` is not dependent on the aligner, it works with both. By the way, the latest dev version also supports local alignments, so there might be a new option (at least for single-cell or PBAT-type alignments) needed soon. Greetings from France!

**Comment by phue** [comment]
Hi @ewels and @FelixKrueger 

Thanks for your comments!

If bismark is doing the sanity checking, I guess it's safe to omit that here.

I added a `--slamseq` flag to convert the reference genome accordingly. This of course makes a lot more sense when using hisat2 in a splice-aware manner.

For splice-aware mapping, a .gtf file should be provided, which is converted to the correct input format using HISAT2's `hisat2_extract_splice_sites.py` 
This is the quick way of doing that by bash process substitution. We could also think about a separate process for that as implemented in the RNAseq pipeline:
https://github.com/nf-core/rnaseq/blob/37f260d360e59df7166cfd60e2b3c9a3999adf75/main.nf#L364

I  updated the documentation accordingly and added the new `bismark_hisat` case to the travis file.
Tests are failing because the docker container needs to be updated first.

**Comment by apeltzer** [comment]
This fails because its missing in the hisat2, so we shold just merge once @phue added the missing dependencies here and I'll merge that to `dev` then afterwards to get the container built again.

**Pull request merged**
