### PR TITLE
Version bump for 1.2

### PR DESCRIPTION
**Pull request by ewels**
Bumping the version for a v1.2 release.

Note that this should also test the changes to the docker container built in #57

### CODE REVIEW

**Comment by ewels** [comment]
FastQC update from #57 is broken :(

**Comment by apeltzer** [comment]
Add: 

```
 - font-ttf-dejavu-sans-mono=2.37 #for fastqc 
 - fontconfig=2.12.6
```

to the `environment.yaml`. Fontconfig should already be pulled by FastQC recipe, but the font isn't.

**Comment by ewels** [comment]
Sigh, needs a release on nf-core tools I guess.. Are we happy to push the pipeline release anyway? Or maybe we should do a minor release on nf-core/tools?

**Comment by apeltzer** [comment]
I'M happy with it - just do the release!

**Pull request merged**
