### PR TITLE
apply snake_case naming scheme to all parameters

### PR DESCRIPTION
**Pull request by phue**
consistency FTW!

### CODE REVIEW

**Comment by phue** [comment]
Tests fail because of some java problem with nextflow `0.32.0`, should we bump the required nextflow version to something more recent?

**Comment by drpatelh** [comment]
Yep. Bumping to `19.04.0` should fix that. Nice to see you are standardising the parameter convention here too :+1: 

Could you just check these against the `dev` of `nf-core/chipseq` e.g. I remamed to `save_align_intermeds` to trim it down a little. Also, `igenomesIgnore` should be `snake_case` in the template too. Can have a proper look at this PR tomorrow.

**Comment by phue** [comment]
> `igenomesIgnore` should be `snake_case`

I didn't change that because some configs use `igenomesIgnore`, this might break things

**Comment by ewels** [comment]
> I didn't change that because some configs use `igenomesIgnore`, this might break things

True, we should go through all nf-core/configs and set both `igenomesIgnore` _and_ `igenomes_ignore`

**Comment by drpatelh** [comment]
Yep. Agreed. There is no harm in having both set until `igenomesIgnore` is eventually removed from all pipelines via the template syncing.

**Comment by ewels** [comment]
We should update the linter to fail if `igenomesIgnore` is found..

**Comment by phue** [comment]
also, the linter throws a warning regarding `params.singleEnd`
```
http://nf-co.re/errors#4: Config variable not found: params.singleEnd
```

**Comment by ewels** [comment]
Yes, we should update this too.. 🤦‍♂

**Comment by ewels** [comment]
(and fail if `--singleEnd` is found)

**Comment by ewels** [comment]
https://github.com/nf-core/tools/pull/438

**Comment by drpatelh** [comment]
Something weird going on with the tabbing here @phue ? 
https://github.com/nf-core/methylseq/blob/8718e1798eea3fa40648601c567d49c2589c7f80/main.nf#L24-L54

I realise you have a `parameters.settings.json` file but it would be good if you can have a variable type declaration in that section. Seeing as we are now moving everything to `snake_case` it would be good to provide some information as to the expected input values. e.g.
https://github.com/nf-core/chipseq/blob/dbfc692da159e660e69a0801f2d9fe0ba9303fbc/main.nf#L21-L83

**Comment by phue** [comment]
@ewels @drpatelh 
I opened a PR to update the configs to include both `igenomesIgnore` and `igenomes_ignore` :
https://github.com/nf-core/configs/pull/77

**Comment by phue** [comment]
not sure what's the problem here:

```
http://nf-co.re/errors#9: Could not find Dockerfile file string: FROM nfcore/base:1.7
```

**Comment by drpatelh** [comment]
You need to change the first line in the `Dockerfile` to contain that string:
https://github.com/nf-core/tools/blob/dev/nf_core/pipeline-template/%7B%7Bcookiecutter.name_noslash%7D%7D/Dockerfile

**Comment by phue** [comment]
Thanks, missed that

**Comment by phue** [comment]
Tests are passing now. :tada: 

I'd like to also sync the latest `TEMPLATE` branch to prepare for `1.4` release, but I'm a bit lost here.
Isn't the bot supposed to update the `TEMPLATE` branch with every `tools` release, wihch would then allow me to do a `git merge TEMPLATE` to the current branch?
Somehow that didn't happen, or where am I getting the process wrong? :confused:

**Comment by drpatelh** [comment]
The automated syncing across pipelines didnt work on the last release. @ewels has written the scripts to do this in order to give us a finer level of control. I manually updated the pipelines Im working on using the latest template but Im sure @ewels probably has a niftier way of doing this with the new implementation.

**Comment by ewels** [comment]
I will run locally and make a PR for that separately.

**Pull request merged**
