### PR TITLE
Tools 2.7.1 merge

### PR DESCRIPTION
**Pull request by ewels**
Fixes merge conflicts in #287

#287 should automatically show as merged when this PR is merged. Keeping them separate so that it's easier to compare diffs.

### CODE REVIEW

**Review by njspix — COMMENTED** [review]
I was hoping to be helpful, but since many of the changes are in the .github magic (which I don't understand very well), I'm afraid I don't have much to contribute. 
but if you need a rubber stamp I'm happy to be that! 😄

**Review by njspix — APPROVED** [review]

**Comment by ewels** [comment]
Thanks @njspix!

I'm a bit worries that the tests are taking many hours to run.. Might be worth investigating before I merge.. 🤔

**Review by Emiller88 — APPROVED** [review]
Looks great!

**Comment by ewels** [comment]
Tests were hanging due to https://github.com/nf-core/tools/issues/2132

Reverted change, should hopefully pass again now.

**Comment by ewels** [comment]
That's better!

**Pull request merged**
