### PR TITLE
Add length_trim parameter to config file

### PR DESCRIPTION
**Pull request by geethavenk**
Included a new parameter, length_trim, to allow users to specify the minimum acceptable read length after quality and adapter trimming. This enhancement provides greater flexibility in handling quality trimming.

## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/methylseq/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, also make a PR on the nf-core/methylseq _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Check for unexpected warnings in debug mode (`nextflow run . -profile debug,test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Comment by geethavenk** [comment]
@sateeshperi I have changed the base. Thank you!

**Review by sateeshperi — APPROVED** [review]
Thank you

**Review by sateeshperi — CHANGES_REQUESTED** [review]
@geethavenk 

A change that is coming with the workflow-updates PR is that there is no more a `conf/modules.config` and each module gets its own `nextflow.config` along with its `main.nf` file.

Could you update to adding the param to `modules/nf-core/trimgalore/nextflow.config` instead of in `conf/modules.config` ?

**Comment by geethavenk** [comment]
@sateeshperi 

I will create a new pull request after changing the `modules/nf-core/trimgalore/nextflow.config`. Could you please let me know what should be added in the CHANGELOG?

Thank you!

**Comment by sateeshperi** [comment]
in CHANGELOG -> under Pipeline Updates

🔧 Add new trimgalore length trim param https://github.com/nf-core/methylseq/pull/<PR-number>

**Comment by geethavenk** [comment]
@sateeshperi 
I have made a new PR #416 including the required changes.

**Pull request closed without merging**
