### PR TITLE
Move warning messages below initial log. Stop ignoring failures.

### PR DESCRIPTION
**Pull request by ewels**
Also stopped running a couple of processes with the `local` executor, as this breaks stuff for people running on kubernetes...

### CODE REVIEW

**Comment by MaxUlysse** [comment]
Is there a particular reason for that?

**Comment by ewels** [comment]
For which bit?

**Comment by MaxUlysse** [comment]
the Stop ignoring failures part

**Comment by ewels** [comment]
Oh, basically because I don't think that they should be failing. Now that we are using containers everything should be more stable, and ignoring failures means that they don't show up in the tests. Hopefully we won't be having enough failures for it to be a problem for people running the pipeline.

We can add this back if you think it's a bad idea.

**Comment by MaxUlysse** [comment]
I don't think so, I was just wondering what was the motivation behind.

**Pull request merged**
