### PR TITLE
Template sync

### PR DESCRIPTION
**Pull request by phue**
This should finally close https://github.com/nf-core/methylseq/issues/44

There were quite a few merge conflicts, so we should test it properly...

Most notable changes to match the features according to the template

* added a helpMessage
* added r-markdown as a dependency that is needed to render the output info html
* removed deprecated installation.md as this information is now on the website
* removed NGI logos and references as we now use nf-core logos only ( I hope this is OK @ewels )

### CODE REVIEW

**Comment by phue** [comment]
There seems to be a small bug with the recent addition of `bismark_hisat` as an aligner option, that only occurs when there is more than one CPU available for the alignment step. Travis tests pass because this particular case is not covered.

I submitted https://github.com/FelixKrueger/Bismark/pull/250 upstream that should fix the issue but we probably have to wait for a new bismark release before releasing this.

**Comment by phue** [comment]
Other than that, this is fine for merging to `dev` (the bug already exists in the dev branch anyway)

We just need to bump the software version(s) **before** releasing 1.4

**Comment by phue** [comment]
@ewels:
 Would be nice to add the HiSAT indices to the iGenomes bucket aswell.
I have no clue how these AWS things work, do you have any pointers for me? :)

**Comment by ewels** [comment]
Awesome! I'm away on leave now so don't have time to review sorry. Hopefully someone else can do so and merge though 👍 

For AWS, it's a bit tricky as it's not very community-run yet. It's basically just me. In the past we've done it by someone else creating an AWS s3 bucket with all of the files organised in the correct directory structure, then I just run the sync command between the two buckets. Needs care though, so I'd recommend doing this when I'm back after the summer. Feel free to make an issue for it on https://github.com/ewels/AWS-iGenomes 🤔 

Phil

**Comment by apeltzer** [comment]
Can review after Easter - on holiday atm

**Pull request merged**
