### PR TITLE
Update --meth_cutoff default to 5 reads, and docs

### PR DESCRIPTION
**Pull request by colindaven**
Hi Phil, good idea, looks better now.

See https://github.com/nf-core/methylseq/pull/49

Hope that hits the spot.

Colin

### CODE REVIEW

**Comment by ewels** [comment]
Hi @colindaven,

This PR is still waiting for your updates. I think I can finish it for you fairly quickly though, so I'll take a look in to this now.

Phil

**Comment by ewels** [comment]
Closing this now, commits are still present in https://github.com/nf-core/methylseq/pull/84, just with some additional work from me.

Phil

**Comment by colindaven** [comment]
Thanks Phil. Apologies, was on my Todo list but core unit bioinformaticians rarely get a chance to get away from data analysis and do some dev work (esp from Nov-March).

**Comment by ewels** [comment]
No problem! It was pretty quick and I already had the code open for other issues 😄 

I hope it's useful! Let me know if you hit any problems..

**Pull request closed without merging**
