### PR TITLE
Bump version number for v1.4.1 release

### PR DESCRIPTION
**Pull request by ewels**
Bumped version number ready for the v1.4.1 minor release

### CODE REVIEW

**Comment by phue** [comment]
I think we might have another `python` problem here :

```
     >>> Now performing quality (cutoff '-q 20') and adapter trimming in a single pass for the adapter sequence: 'AGATCGGAAGAGC' from file LowerStem_D2_single.fastq <<< 

  ERROR: Running in parallel is not supported on Python 2

  Cutadapt terminated with exit signal: '256'.

  Terminating Trim Galore run, please check error message(s) to get an idea what went wrong...
```

**Comment by ewels** [comment]
Argh! So cutadapt needs python 3 and HISAT2 needs python 2?

**Comment by phue** [comment]
> Argh! So cutadapt needs python 3 and HISAT2 needs python 2?

seems like :disappointed:

**Comment by phue** [comment]
> Argh! So cutadapt needs python 3 and HISAT2 needs python 2?

seems like :disappointed:

**Comment by apeltzer** [comment]
But that shouldn't be the case - its one of the tools running `2to3` so it should be running on python3 - see the bioconda build script for the recipe [here](https://github.com/bioconda/bioconda-recipes/blob/master/recipes/hisat2/build.sh)!

**Comment by ewels** [comment]
Yes, but then the python 3 builds are skipped anyway. I already made an issue asking why: https://github.com/bioconda/bioconda-recipes/issues/18911

I might try to prep a PR to enable py3k builds again and see what happens.

**Comment by apeltzer** [comment]
https://github.com/bioconda/bioconda-recipes/pull/19100 once that is in, this should work again. Just need to use the latest hisat2 recipe then, which should be python3 compatible --> done 👍

**Comment by ewels** [comment]
HiSAT2 should now be py3k compatible on bioconda! 🎉 

Added Python 3 back as a requirement here. This PR should be merged then we'll need another PR to test again.

**Comment by phue** [comment]
Great stuff! `MultiQC 1.8` should also work then?

**Comment by apeltzer** [comment]
Yes !

**Pull request merged**
