### PR TITLE
Add preseq

### PR DESCRIPTION
**Pull request by ewels**
Moved from #63 as now in a branch.

---

Adds preseq as a new step to the pipeline. Addresses #62

Note that the step fails in tests, probably because the test data is on lambda and very tiny - not sure? Needs testing with a proper dataset.

### CODE REVIEW

**Comment by ewels** [comment]
preseq failing due to small test data size:
```
ERROR:	Library expected to saturate in doubling of size, unable to extrapolate
```

Set to ignore, so CI tests _should_ still pass.

**Comment by apeltzer** [comment]
I believe its either failing and ignore or providing e.g. a histogram directly to preseq - its a bit finicky that tool ...

**Comment by apeltzer** [comment]
Still software versions failing.

**Comment by apeltzer** [comment]
First thought its a container not containing certain dependencies problem, but that seems not to be the case at all. 

Next, I don't know why but I had to add lots of these `2>&1 || true` statements for `hlatyping` - maybe that fixes your issues here? Otherwise, I didn't have any output in some of these cases here.

**Comment by ewels** [comment]
Yes - I had to do the same earlier to get it to work too (maybe we should just add those to all version commands in the future to be safe?). But in this case the software versions check is working locally but on on travis. That doesn't follow the usual pattern.

I've restarted Travis and will refresh docker / cache etc locally and have a play.

**Comment by ewels** [comment]
oh - travis will also fail on this PR because the docker image doesn't have preseq installed until we merge this PR. But it's failing locally for a different reason... ¯\\_(ツ)_/¯

**Comment by ewels** [comment]
Ah yeah - that's what's happening here. `127` is a bash exit code meaning command not found. Should work once merged to master.

On a separate note, need to push the new tools release and update this pipeline (and others) to use `:dev` for the docker containers. But that won't help here and I'm going to do a release today anyway.

**Comment by ewels** [comment]
Retested and confirmed - works fine with the updated docker container 👍

**Pull request merged**
