### PR TITLE
Add GRCh38

### PR DESCRIPTION
**Pull request by alneberg**
Adding GRCh38 as a reference genome option, even though it is the NCBI version and not the ensembl version.

### CODE REVIEW

**Comment by apeltzer** [comment]
No, this is something @ewels addressed already in here: https://github.com/nf-core/tools/pull/234 
However, the tools weren't release after that, so this is just in the `dev` branch of nf-core tools....

**Comment by ewels** [comment]
Re-ran the tests, now passing 👍 

Should we add some docs pointing out that GRCh38 is NCBI instead of ensembl?

**Comment by alneberg** [comment]
Closed as the changes seems to be in dev already now.

**Comment by ewels** [comment]
Ah sorry! Yes this would have been part of the template sync..

**Pull request closed without merging**
