### PR TITLE
Update Modules

### PR DESCRIPTION
**Pull request by eperezme**
The main thing about this pull request is to update the modules to its latest releases so the pipeline stays alive.

- Updated all modules to the latest version.
- Added empty lists to samtools_sort inputs as new version expects an optional input
- Added empty lists to new optional imputs of multiqc

Any review and improving is wellcomed as this is my first pull request on an external repository

## PR checklist

- [x] This comment contains a description of changes (with reason).
- [x] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).

The test suite does not pass as the PRESEQ module errors even on the unmodified version.

### CODE REVIEW

**Review by edmundmiller — CHANGES_REQUESTED** [review]
Thanks for taking care of this chore! 

> The main thing about this pull request is to update the modules to its latest releases so the pipeline stays alive.

Could you clarify what you mean by "so the pipeline stays alive"? Are you having a bug with the modules?

Also, please rebase this PR off the `dev` branch. It looks like it was branched off master, so that's going to cause a weird history.

I think we fixed the preseq tests failing #382 as well.

Thanks for the contribution!

**Comment by sateeshperi** [comment]
hey @eperezme thanks for this but, I am starting a maintain cycle which will include the module updates. you can close this or rebase off dev so we can review and merge. lmk soon. Thanks again

**Comment by eperezme** [comment]
If @sateeshperi is going to update the modules then there is no need for this pull request. I will close it. Thanks <3

**Comment by sateeshperi** [comment]
I see you put in effort to update the test data paths and use the nft-bam plugin. Thank you @eperezme I will make sure to include your contributions in the changelog

**Pull request closed without merging**
