### PR TITLE
Bump version to v1.5

### PR DESCRIPTION
**Pull request by ewels**
Bump to version 1.5. See https://github.com/nf-core/methylseq/pull/133 for details.

### CODE REVIEW

**Comment by ewels** [comment]
Maybe wait to resolve this merge conflict until the new docker image is built?

**Comment by ewels** [comment]
Then we get to test the pipeline with the new software updates as a bonus

**Comment by ewels** [comment]
Build is here: https://hub.docker.com/repository/registry-1.docker.io/nfcore/methylseq/builds/c31a7c6f-422b-4c82-9687-0caef2452da3

**Comment by ewels** [comment]
Build failed 😞 

```
Package python-dateutil conflicts for:
bioconda::multiqc=1.8 -> click -> python-dateutil
```

I'll test locally and see if I can fix it.

**Comment by ewels** [comment]
ok, hopefully got the build working again by reverting the changes to Python, Samtools and Bowtie2. New docker image building here: https://hub.docker.com/repository/registry-1.docker.io/nfcore/methylseq/builds/3a7bbaf3-0e58-4620-b128-39415ee178ec

**Comment by ewels** [comment]
Build worked! ✅ Fixed the merge conflict - hopefully the tests will pass and we can go forward with the release...

**Comment by ewels** [comment]
Sigh. I should just not ever update anything.

```python
    File "/opt/conda/envs/nf-core-methylseq-1.4.1/lib/python3.7/site-packages/markdown/core.py", line 387, in markdown
      md = Markdown(**kwargs)
    File "/opt/conda/envs/nf-core-methylseq-1.4.1/lib/python3.7/site-packages/markdown/core.py", line 97, in __init__
      configs=kwargs.get('extension_configs', {}))
    File "/opt/conda/envs/nf-core-methylseq-1.4.1/lib/python3.7/site-packages/markdown/core.py", line 125, in registerExtensions
      ext._extendMarkdown(self)
    File "/opt/conda/envs/nf-core-methylseq-1.4.1/lib/python3.7/site-packages/markdown/extensions/__init__.py", line 77, in _extendMarkdown
      self.extendMarkdown(md)
    File "/opt/conda/envs/nf-core-methylseq-1.4.1/lib/python3.7/site-packages/pymdownx/extra.py", line 60, in extendMarkdown
      md.registerExtensions(extra_extensions, self.config)
    File "/opt/conda/envs/nf-core-methylseq-1.4.1/lib/python3.7/site-packages/markdown/core.py", line 125, in registerExtensions
      ext._extendMarkdown(self)
    File "/opt/conda/envs/nf-core-methylseq-1.4.1/lib/python3.7/site-packages/markdown/extensions/__init__.py", line 77, in _extendMarkdown
      self.extendMarkdown(md)
    File "/opt/conda/envs/nf-core-methylseq-1.4.1/lib/python3.7/site-packages/pymdownx/extrarawhtml.py", line 30, in extendMarkdown
      extra.MarkdownInHtmlProcessor(md.parser), 'markdown_block', 105
  AttributeError: module 'markdown.extensions.extra' has no attribute 'MarkdownInHtmlProcessor'
```

**Comment by ewels** [comment]
Ah, same bug is reported here: https://github.com/nf-core/tools/issues/571

**Comment by ewels** [comment]
New build: https://hub.docker.com/repository/registry-1.docker.io/nfcore/methylseq/builds/b392523f-4817-4335-af62-7b3f2eb258cc

**Comment by phue** [comment]
I can't reproduce the latest error locally :(

**Comment by ewels** [comment]
> I can't reproduce the latest error locally :(

Me either - so I figured it was something weird with the GitHub actions commands. I simplified them a little and now it's working 😄

**Pull request merged**
