### PR TITLE
trim galore multicore

### PR DESCRIPTION
**Pull request by phue**
Many thanks to contributing to nf-core/methylseq!

Please fill in the appropriate checklist below (delete whatever is not relevant). These are the most common things requested on pull requests (PRs).

## PR checklist
 - [x] This comment contains a description of changes (with reason)
 - [x] Ensure the test suite passes (`nextflow run . -profile test,docker`).
 - [x] Make sure your code lints (`nf-core lint .`).
 - [ ] Documentation in `docs` is updated
 - [x] `CHANGELOG.md` is updated

**Learn more about contributing:** https://github.com/nf-core/methylseq/tree/master/.github/CONTRIBUTING.md

This adds support for running TrimGalore/cutadapt with multiple cores. 
Adapted from https://github.com/nf-core/atacseq/pull/65

### CODE REVIEW

**Comment by phue** [comment]
right, changed the logic.

I think we should also lower the memory requirement of the `trim_galore` process. 16GB seems a bit over the top. How does 4GB sound to you?

**Comment by ewels** [comment]
> How does 4GB sound to you?

Not sure - may need testing with the multicore approach first. I guess that @felixkrueger [means](https://github.com/nf-core/atacseq/pull/65#issuecomment-557840070) that we need 2GB memory _per core_ used. Or per `--core` used?? So if we're now using 12 cores then 16GB may not be so crazy.

Note that we should probably update `base.config` to be `15` instead of `12` with the new logic..

**Comment by FelixKrueger** [comment]
Hi guys, sorry for the slow reply. I have just run a test on 2M paired-end files, 

`-j  1`: 0.55G
`-j  2`:  1.22G
`-j  4`: 1.67G
`-j  8`: 2.58G
`-j 12`: 3.48G

So I agree that 16GB seems a bit excessive. If it will never exceed 4GB I can't tell from this one test, I suppose ifsomeone is using really long reads it might go up somewhat...

**Comment by ewels** [comment]
Thank you for testing @FelixKrueger! Let's go for 6GB, middle ground. Doesn't seem too bad given the number of cpus we're running with.

**Comment by ewels** [comment]
@phue - looking good 👍 I'll merge now and incorporate the memory change into my upcoming patch PR.

**Pull request merged**
