### PR TITLE
bwameth align - touch files

### PR DESCRIPTION
**Pull request by ewels**
bwameth align - touch files to avoid index build error. See for example: https://github.com/nf-core/methylseq/runs/2564102125?check_suite_focus=true

```python
  Traceback (most recent call last):
    File "/opt/conda/envs/nf-core-methylseq-1.7dev/bin/bwameth.py", line 509, in <module>
      main(sys.argv[1:])
    File "/opt/conda/envs/nf-core-methylseq-1.7dev/bin/bwameth.py", line 502, in main
      bwa_mem(args.reference, conv_fqs_cmd, ' '.join(map(str, pass_through_args)),
    File "/opt/conda/envs/nf-core-methylseq-1.7dev/bin/bwameth.py", line 315, in bwa_mem
      raise BWAMethException("first run bwameth.py index %s" % fa)
  __main__.BWAMethException: first run bwameth.py index genome.fa
  [main_samview] fail to read the header from "-".
```

Discovered by @Shabhonam and reported [on the nf-core Slack](https://nfcore.slack.com/archives/CP3RJSMF0/p1624002989043500).

> Looking at the bwameth.py source, it seems this is due to a check whether one file is newer than another: https://github.com/brentp/bwa-meth/blob/master/bwameth.py#L315

This PR incorporates his fix into the pipeline - adding a `touch` command to update the modified timestamps on the reference files before running.

## PR checklist

- [x] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
  - [ ] If you've added a new tool - add to the software_versions process and a regex to `scrape_software_versions.py`
  - [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/methylseq/tree/master/.github/CONTRIBUTING.md)
  - [ ] If necessary, also make a PR on the nf-core/methylseq _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [x] Make sure your code lints (`nf-core lint .`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [x] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Review by FriederikeHanssen — APPROVED** [review]
looks good

**Comment by wangshun1121** [comment]
v 1.6.1 pipeline still has this error! why not merge branch `6e78cf072724158c50dc223be9194316e5ce60c8` to main branch?

**Comment by ewels** [comment]
Yes we should do a patch release. At the time I thought a major release was imminent but it hasn't happened yet.

**Comment by PanZiwei** [comment]
It seems that `v2.1.0` is still has the error below.

```
Error executing process > 'NFCORE_METHYLSEQ:METHYLSEQ:ALIGNER:BWAMETH_ALIGN (PC3)'

Caused by:
  Process `NFCORE_METHYLSEQ:METHYLSEQ:ALIGNER:BWAMETH_ALIGN (PC3)` terminated with an error exit status (1)

Command executed:

  INDEX=`find -L T2T-CHM13v2.0_MT.fna.bwameth.c2t -name "*.bwameth.c2t" | sed 's/.bwameth.c2t//'`
  
  # Modify the timestamps so that bwameth doesn't complain about building the index
  # See https://github.com/nf-core/methylseq/pull/217
  touch -c -- *
  
  bwameth.py \
       \
       \
      -t 12 \
      --reference $INDEX \
      PC3_1_val_1.fq.gz PC3_2_val_2.fq.gz \
      | samtools view  -@ 12 -bhS -o PC3.bam -
  
  cat <<-END_VERSIONS > versions.yml
  "NFCORE_METHYLSEQ:METHYLSEQ:ALIGNER:BWAMETH_ALIGN":
      bwameth: $(echo $(bwameth.py --version 2>&1) | cut -f2 -d" ")
  END_VERSIONS

Command exit status:
  1

Command output:
  (empty)

Command error:
  Traceback (most recent call last):
    File "/usr/local/bin/bwameth.py", line 4, in 
      __import__('pkg_resources').run_script('bwameth==0.2.2', 'bwameth.py')
    File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 657, in run_script
      self.require(requires)[0].run_script(script_name, ns)
    File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1437, in run_script
      exec(code, namespace, namespace)
    File "/usr/local/lib/python3.7/site-packages/bwameth-0.2.2-py2.7.egg-info/scripts/bwameth.py", line 509, in 
      main(sys.argv[1:])
    File "/usr/local/lib/python3.7/site-packages/bwameth-0.2.2-py2.7.egg-info/scripts/bwameth.py", line 506, in main
      set_as_failed=args.set_as_failed)
    File "/usr/local/lib/python3.7/site-packages/bwameth-0.2.2-py2.7.egg-info/scripts/bwameth.py", line 315, in bwa_mem
      raise BWAMethException("first run bwameth.py index %s" % fa)
  __main__.BWAMethException: first run bwameth.py index T2T-CHM13v2.0_MT.fna

Work dir:
  /gpfs/ctgs0/fastscratch/c-panz/ecdna/WGS_nf_methylseq/work/d9/5ceb451335d5811adb70efb142f595

Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line
```

**Pull request merged**
