### PR TITLE
add runOptions to Docker profile to fix ownership on files

### PR DESCRIPTION
**Pull request by MaxUlysse**
Add runOptions to Docker profile to fix ownership on files.
Otherwise we have `Permission denied` when deleting the work directory.

### CODE REVIEW

**Comment by ewels** [comment]
This makes me a little nervous. Will it have any off-target affects?

@pditommaso - why is this not the default in Nextflow?

**Comment by MaxUlysse** [comment]
There was also the [fixOwnership setting](https://www.nextflow.io/docs/latest/config.html#scope-docker) in the Docker scope

**Comment by ewels** [comment]
> There was also the fixOwnership setting in the Docker scope

Does this have the same effect? I'm a bit scared of changing these kinds of defaults in case it breaks everything for people running say, kubernetes.

**Comment by MaxUlysse** [comment]
If I remember well, I think I had the `fixOwnership` and it might have caused some issue when I tried AWS, so @pditommaso told me to use this `docker.runOptions = '-u $(id -u):$(id -g)'`.
And no problem with Docker on AWS, but haven't tried kubernetes yet ;-)

**Comment by pditommaso** [comment]
>  why is this not the default in Nextflow?

Well, this was a long discussion (with myself). To summarise the idea was to make it the default, but then I've realised that when using that setting also the container `USER` and home path are different that potentially could have some negative side effects 

https://github.com/nextflow-io/nextflow/issues/515

**Comment by ewels** [comment]
> this was a long discussion (with myself)

I know the feeling 😅 

I'd be tempted to leave this out of nf-core pipelines for now then - same risk of pros & cons and could be resolved in a future core nextflow release anyway.

**Comment by ewels** [comment]
Closing for now @MaxUlysse - hope that's ok! Maybe submit a PR with some documentation describing this and how to fix with a user config under a troubleshooting section?

**Comment by MaxUlysse** [comment]
Ah, yes, I had questions, that's why I didn't merge it.
Sorry that I forgot to merge

**Pull request closed without merging**
